---
pacman_packages:
  - alacritty
  - alsa-utils
  - audacity
  - base
  - base-devel
  - bind
  - bluez
  - bluez-utils
  - breeze
  - cifs-utils
  - copyq
  - docker
  - docker-compose
  - dosfstools
  - fd
  - firefox
  - freerdp
  - fzf
  - git
  - gnome-calculator
  - go
  - grim
  - gvfs
  - hypridle
  - hyprlock
  - imagemagick
  - jq
  - kdiff3
  - less
  - lib32-libpulse
  - lib32-nvidia-utils
  - linux
  - linux-firmware
  - linux-headers
  - mako
  - networkmanager
  - nfs-utils
  - niri
  - nodejs
  - npm
  - nvidia-open
  - nvidia-settings
  - nvidia-utils
  - obsidian
  - openssh
  - pacman-contrib
  - pipewire-alsa
  - pipewire-pulse
  - prismlauncher
  - python-pipx
  - qt5-quickcontrols2
  - remmina
  - rofi
  - rsync
  - sddm
  - slurp
  - steam
  - sudo
  - swappy
  - swaybg
  - syncthing
  - thunar
  - thunar-volman
  - unzip
  - uv
  - vim
  - waybar
  - wget
  - wimlib
  - wireplumber
  - xwayland-satellite
  - zoxide
  - zsh

aur_packages:
  - google-chrome
  - nordvpn-bin
  - rtl8821au-dkms-git
  - synology-drive
  - visual-studio-code-bin
