---
- name: Install Artix OpenRC service init scripts
  command: pacman -S --needed --noconfirm bluez-openrc docker-openrc networkmanager-openrc openssh-openrc
  register: openrc_packages_result
  changed_when: "'installing' in openrc_packages_result.stdout"

- name: Install lemurs login manager
  command: pacman -S --needed --noconfirm lemurs
  register: lemurs_result
  changed_when: "'installing' in lemurs_result.stdout"
