---
- name: Check if paru is installed
  command: pacman -Qi paru
  register: paru_check
  failed_when: false
  changed_when: false

- name: Install paru build dependencies
  command: pacman -S --needed --noconfirm rust
  when: paru_check.rc != 0

- name: Clone paru from AUR
  git:
    repo: https://aur.archlinux.org/paru.git
    dest: /home/{{ ansible_user }}/.cache/paru-build
  when: paru_check.rc != 0
  become: yes
  become_user: "{{ ansible_user }}"

- name: Build paru
  command: makepkg -sf --noconfirm
  args:
    chdir: /home/{{ ansible_user }}/.cache/paru-build
  when: paru_check.rc != 0
  become: yes
  become_user: "{{ ansible_user }}"

- name: Install paru
  shell: pacman -U --noconfirm /home/{{ ansible_user }}/.cache/paru-build/*.pkg.tar.zst
  when: paru_check.rc != 0

- name: Check AUR package installed
  command: pacman -Qi {{ item }}
  loop: "{{ aur_packages + machine_specific_aur_packages }}"
  register: aur_check
  failed_when: false
  changed_when: false

- name: Install AUR packages
  command: paru -S --noconfirm {{ item.item }}
  loop: "{{ aur_check.results }}"
  when: item.rc != 0
  become: yes
  become_user: "{{ ansible_user }}"
