---
- name: Update pacman cache
  community.general.pacman:
    update_cache: yes
  check_mode: no

- name: Install official packages
  community.general.pacman:
    name: "{{ pacman_packages + machine_specific_pacman_packages }}"
    state: present
