---
- name: Update pacman cache
  community.general.pacman:
    update_cache: yes
  check_mode: no

- name: Install official packages
  command: >-
    pacman -S --needed --noconfirm
    {{ (pacman_packages + machine_specific_pacman_packages) | join(' ') }}
  register: pacman_result
  changed_when: "'installing' in pacman_result.stdout or 'upgrading' in pacman_result.stdout"
