---
- import_tasks: config.yml
- import_tasks: services.yml
- import_tasks: fonts.yml
  tags: fonts
- import_tasks: wallpaper.yml
  tags: wallpaper
- import_tasks: brightness.yml
  when: has_backlight | default(false)
  tags: brightness
